all: thread_create thread_create_simple_args thread_create_with_return_args

thread_create:
	cargo run --bin thread_create

thread_create_simple_args:
	cargo run --bin thread_create_simple_args

thread_create_with_return_args:
	cargo run --bin thread_create_with_return_args
