all: 
	cargo run --bin ${bin}

rwlock:
	cargo run --bin rwlock 10000 10000

producer_consumer_works:
	cargo run --bin producer_consumer_works 1000 100 10

throttle:
	cargo run --bin throttle 1000 100

dining_philosophers_no_deadlock:
	cargo run --bin dining_philosophers_no_deadlock 1000

dining_philosophers_deadlock:
	cargo run --bin dining_philosophers_deadlock 1000

dining_philosophers_no_deadlock_print:
	cargo run --bin dining_philosophers_no_deadlock_print 1000

dining_philosophers_deadlock_print:
	cargo run --bin dining_philosophers_deadlock_print 1000
